### ISSUE TITLE
Teleportation Problems

### ISSUE THREAD

**Issue by Marsypwn** [FishingCactus/NanotaleEarlyAccessBugs#102]
Good Evening! 
      I was playing this game, enjoying it quite thoroughly, I just got to the first battle with the queen. I beat her and then one of the forest people gave me the ability to teleport. All was fine and dandy until I teleported all the way to the top of the tree and realized I didn't have any mana to burn the corruption. I went to go back down the tree to get a mana thingy, but the word for the teleportation did not show up. I did respawn, that didnt work. I restarted the game, and the game updated. (The update released while I was playing) and now when I load back in I am stuck in just the middle part of the tree. Only certain teleportation pads are working. The ones I need to continue to move forward are not showing the words to type them. Please help. 

Thank you. :)

**Comment by mxrowan** [comment]
Seconding this issue as still open, no solution that I've found!

I got to the top and finished the game (burning that corruption is the end of Early Access as of 1/5/2020, if you were curious, Marsypwn). I loaded the save to see if I could continue exploring and encountered this problem on my way down the tree. I'm stuck in the middle part; I've tried reloading the game a couple times and managed to break another teleport pad to the side of the path, but not fix either of the pads I needed going up OR down. RESPAWN seems to treat each teleport as a checkpoint, so it's not getting me anywhere either.

I can see the pads and know they're not blocked by anything to be burned (killed an enemy with LARGE FIRE near it) but the word to activate does not appear. 

Thanks, still, for the continued development on a great game!

Upper end broken pad (left of screen):
![endgame teleport upper](https://user-images.githubusercontent.com/59551242/71797077-a7c1cb80-301a-11ea-9590-dc9e68088fb6.png)

After reloading, with a previously-working pad (top of screen) now broken:
![endgame teleport middle](https://user-images.githubusercontent.com/59551242/71797151-d93a9700-301a-11ea-9035-14540a707605.png)

Lower end broken pad (right of screen):
![endgame teleport lower](https://user-images.githubusercontent.com/59551242/71797092-b27c6080-301a-11ea-8743-47e8f9c51655.png)

**Comment by ZinaDerudder** [comment]
Hello people.
Thank you for your report =)
There was an issue impacting the teleporters covered by brambles.
Now this is fixed in the current version on steam (patched on the 6th February).
You should be able to teleport without any problem.
If you are still facing this situation, please let us know.
