### ISSUE TITLE
Sheep Quest

### ISSUE THREAD

**Issue by Kali36500** [FishingCactus/NanotaleEarlyAccessBugs#104]
After all five sheep have been gathered, the forest person thanks the player and they ask them to move the sheep and a journal entry pops up. The issue is the view shifts to the forest person and does not shift back to the player. I have attempted to move into line of sight, zoom in and out, respawn, and even begin the game again from the menu. None have made the main character appear or the camera move away from the forest person.

**Comment by katrina-p** [comment]
I had the same problem.  It went away when I talked to the shepherd again.  I also had the same issue when talking to the shepherd at the start of gathering all 5 sheep.

**Comment by ZinaDerudder** [comment]
Hello @Kali36500 and @katrina-p 
Thank you for your report =)
This issue should be fixed with the current Steam version.
If you are still facing this situation, please let me know.
