### ISSUE TITLE
Game Crash upon Load up

### ISSUE THREAD

**Issue by Yunsildin** [FishingCactus/NanotaleEarlyAccessBugs#105]
Every time I try to load the game to try playing it, it crashes close to finishing it's load up.  I get this message from the error

  Problem Event Name:	APPCRASH
  Application Name:	Nanotale.exe
  Application Version:	2019.1.7.50322
  Application Timestamp:	5cf82580
  Fault Module Name:	UnityPlayer.dll
  Fault Module Version:	2019.1.7.50322
  Fault Module Timestamp:	5cf826fb
  Exception Code:	c0000005
  Exception Offset:	00000000004eb930
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1033
  Additional Information 1:	a002
  Additional Information 2:	a002c51e568b004be00f4ed8263f7cfa
  Additional Information 3:	f307
  Additional Information 4:	f3071f43662ac6ca8134f26f341f5b28

**To Reproduce**
1. Go to Steam
2. Press Play
3. See error after it tries to load the game

**Expected behavior**
I expected to be able to play the game like I was before the update.

**Desktop (please complete the following information):**
 - OS: Windows 7 
 - GTX 970

**Comment by ZinaDerudder** [comment]
Hello @Yunsildin 
Indeed, we've checked that, and it appears that the game does not work on Windows 7 if played windowed mode, and neither on fullscreen 1080p.
We'll try to find a solution for this.

**Comment by ZinaDerudder** [comment]
Hello @Yunsildin 
We've made some modifications, and Nanotale is running perfectly on Windows 7, on any screenmode and any resolution.
Please, if you still have issues, tell us here :)
