### ISSUE TITLE
Game crash on start

### ISSUE THREAD

**Issue by g32** [FishingCactus/NanotaleEarlyAccessBugs#106]
**Describe the bug**
Game crash on start.
Имя события проблемы:	APPCRASH
  Имя приложения:	Nanotale.exe
  Версия приложения:	2019.1.7.50322
  Отметка времени приложения:	5cf82580
  Имя модуля с ошибкой:	UnityPlayer.dll
  Версия модуля с ошибкой:	2019.1.7.50322
  Отметка времени модуля с ошибкой:	5cf826fb
  Код исключения:	c0000005
  Смещение исключения:	00000000004eb930
  Версия ОС:	6.1.7601.2.1.0.256.1
  Код языка:	1049
  Дополнительные сведения 1:	a002
  Дополнительные сведения 2:	a002c51e568b004be00f4ed8263f7cfa
  Дополнительные сведения 3:	700e
  Дополнительные сведения 4:	700ef6e16b3048378661f858de57c0c3

**To Reproduce**
1. Go to Steam
2. Press Play
3. See error

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Graphics device NVIDIA GeForce GTX 1060 6GB

**Comment by g32** [comment]
Game carshes after showing 2 logos

**Comment by g32** [comment]
Game crashes on fullscreen in 1920x1080 resolution and in windowed mode on 1600x900 and 1920x1080, it runs fine in 1600x900 + fullscreen mode.

**Comment by ZinaDerudder** [comment]
Hello @g32 
Indeed, we've checked that, and it appears that the game does not work on Windows 7 if played windowed mode, and neither on fullscreen 1080p.
We'll try to find a solution for this.
