### ISSUE TITLE
Model bug

### ISSUE THREAD

**Issue by FreshisGreat** [FishingCactus/NanotaleEarlyAccessBugs#107]
**Describe the bug**
Model bug.

**To Reproduce**
1. Go to 
![image](https://user-images.githubusercontent.com/58961197/71756914-4cce8e00-2ecd-11ea-8e00-7f2311966135.png)

2. Move around...
3. See error
![image](https://user-images.githubusercontent.com/58961197/71756950-8606fe00-2ecd-11ea-8e4a-7bd8f82e402b.png)
![image](https://user-images.githubusercontent.com/58961197/71757352-278f4f00-2ed0-11ea-8760-340568ea53cc.png)

**Expected behavior**
Model fix.

**Screenshots**
Up there.

**Desktop (please complete the following information):**
 - Windows 10
 - NVIDIA GeForce GTX 1060

**Additional context**
If this is a bug, please fix it. Thanks:)

**Comment by ZinaDerudder** [comment]
Collider has been fixed.
Issue fixed in current Steam build.
