### ISSUE TITLE
Character Stuck just after tutorial

### ISSUE THREAD

**Issue by saberprivateer** [FishingCactus/NanotaleEarlyAccessBugs#108]
During the tutorial you encounter the plants that turn into water after they are hit.  The NPC was up a bit blocking the way but I could see the words for three of the plants on the screen.  I started typing and was interrupted by the "Discovery" dialog.  I typed the words, got the full details and when it was dismissed the NPC ran off, two of the three plants were popped and I couldn't move my character.  I could hear sounds when I typed on the keyboard.  I pressed space, nothing. I pressed escape, nothing.

**Comment by ZinaDerudder** [comment]
Should be fixed now.
Currently, the player should not be able to see more than the 1st water plant, so that the script can't be broken anymore.
