### ISSUE TITLE
Map always uses ESDF movement keys

### ISSUE THREAD

**Issue by jruderman** [FishingCactus/NanotaleEarlyAccessBugs#112]
**Describe the bug**
I set movement to use WASD, but when I view the map, it pans with ESDF instead

**To Reproduce**
1. In game options, set keyboard layout to WASD
2. Press Esc to view the map
3. Try to pan the map by pressing WASD

**Expected behavior**
The map should pan with WASD (and the map key should reflect this)

**Screenshot**
![image](https://user-images.githubusercontent.com/692547/75546490-7bed1180-59dd-11ea-8e03-ac29a51ec52c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by ZinaDerudder** [comment]
Hello Jruderman.
Thank for reporting :).  We'll fix that issue.

**Comment by Ruvah** [comment]
Fixed internally (customizable keybindings update)
