### ISSUE TITLE
Level Up offered me "sharp shell" option even though I already have sharp spell

### ISSUE THREAD

**Issue by jruderman** [FishingCactus/NanotaleEarlyAccessBugs#117]
I already have sharp spell -- I picked it on my previous level up -- so this is weird

![image](https://user-images.githubusercontent.com/692547/75551889-fde33780-59e9-11ea-894b-7591ec9aa4e6.png)

**Comment by ZinaDerudder** [comment]
@jruderman I need to check with our game designer, but I think there are several levels for the sharp spell.
But if it's well so, it needs to be more precise (and say Sharp spell lvl 2, for example).
Thanks for reporting, I'll check that with the team :)
