### ISSUE TITLE
Not able to escape NPC's speech bubble 

### ISSUE THREAD

**Issue by luisehartdegen** [FishingCactus/NanotaleEarlyAccessBugs#118]
**Describe the bug**
Upon encountering the NPC in the forest after the fox brought me there and saying hello to her, I am not able to escape the speech bubble. She says the stuff about me being not from around here and whether I'm lost and after that nothing happens when I press the space bar (or any other key except for esc). 
When I tried respawn the camera stayed on the NPC and my character just vanished. 

**To Reproduce**
1. Quit the game
2. Loaded it again 
3. Went to the NPC and started talking to her again 

**Screenshots**
![Screenshot (1)](https://user-images.githubusercontent.com/62108696/76535640-77b00200-647b-11ea-97e6-e2564d57695d.png)

**Desktop (please complete the following information):**
 - Windows 10

**Comment by ZinaDerudder** [comment]
hello @paperheartedghost 
You have to type the words in capital letters, to progress in the dialogue.
