### ISSUE TITLE
You can push mobs into one wall

### ISSUE THREAD

**Issue by Feelzor** [FishingCactus/NanotaleEarlyAccessBugs#125]
**Describe the bug**
The snails in the screenshot can be pushed into walls with the knockback on.

**To Reproduce**
1. Go to the sunken caves
2. Walk where there are 4 snails, poison and 6 teleporters
3. Attack the snail on the top

**Expected behavior**
The wall should block the snail instead of letting him pass. Although the player cannot walk in it, so only the mob with knockback can go through it.

**Screenshots**
https://imgur.com/a/Doq1SHl

**Desktop:**
 - OS: Windows 10
 - Nvidia RTX 2080

**Comment by ZinaDerudder** [comment]
**Info for team**
Walls colliders should also apply to enemies

**Comment by Ruvah** [comment]
Fix should already be live (:
