### ISSUE TITLE
Heaven's Root doesn't open in the Field notes

### ISSUE THREAD

**Issue by Feelzor** [FishingCactus/NanotaleEarlyAccessBugs#126]
**Describe the bug**
When you open the field notes and click on Heaven's Root (or type it), nothing happens.

**To Reproduce**
1. Go to Field Notes > Plants
2. Find Heaven's Root
3. Click on it

**Expected behavior**
A window with description, level of knowledge and drawing should appear.

**Desktop:**
 - OS: Windows 10
 - Nvidia RTX 2080

**Comment by Feelzor** [comment]
Other plants with the same problem:
- Aurinko
- Punerva

Cultures with the same problem:
- The blue grounds
- Nokken

**Comment by Ruvah** [comment]
Fix should already be live by now
