### ISSUE TITLE
In the field notes, the bubble showing which page is open sometimes doesn't light

### ISSUE THREAD

**Issue by Feelzor** [FishingCactus/NanotaleEarlyAccessBugs#127]
**Describe the bug**
When you open the field notes, there is a white dot on the bottom showing which page is open. But sometimes it is gray, and all dots are gray.

**To Reproduce**
1. Press Plants then Enemies
2. Look at the dots on the bottom

**Expected behavior**
One of the dots on the bottom should be white to show the current page.

**Screenshots**
https://imgur.com/nu6M6pm

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Nvidia RTX 2080

**Comment by ZinaDerudder** [comment]
**Info for team**
When you open a sub menu (plants-culture-etc), occurs everytime.
