### ISSUE TITLE
// Shield lore

### ISSUE THREAD

**Issue by Feelzor** [FishingCactus/NanotaleEarlyAccessBugs#128]
**Describe the bug**
In the enemies lore, there is a `// Shield` with `// Description of the enemy` description.

**To Reproduce**
1. Go to Field Notes
2. Go to Enemies
3. See error

**Expected behavior**
A real name and description should show for this enemy.

**Screenshots**
https://imgur.com/ZCWpigK

**Desktop:**
 - OS: Windows 10
 - Nvidia RTX 2080

**Comment by ZinaDerudder** [comment]
Duplicate of #129
