### ISSUE TITLE
Enemies field notes almost empty

### ISSUE THREAD

**Issue by Feelzor** [FishingCactus/NanotaleEarlyAccessBugs#129]
**Describe the bug**
The Enemies tab of the field notes is almost empty, there is only the `// Shield` enemy (see #128).

**To Reproduce**
1. Go to 'Field notes'
2. Go to 'Enemies'
3. See error

**Expected behavior**
All enemies should be listed here, those seen in the outside too, the different kind of exploding enemies (fire, poison, water), ...

**Screenshots**
https://imgur.com/6avAZp5

**Desktop:**
 - OS: Windows 10
 - Nvidia RTX 2080

**Comment by ZinaDerudder** [comment]
Task left to be done
