### ISSUE TITLE
Tamarai Bush not clickable in the Field Notes

### ISSUE THREAD

**Issue by Feelzor** [FishingCactus/NanotaleEarlyAccessBugs#130]
**Describe the bug**
In the field notes, the Tamarai Bush cannot be clicked on (to see details). It can only be typed.

**To Reproduce**
1. Go to Field Notes > Plants
2. Find Tamarai Bush
3. Click on its name

**Expected behavior**
The description of the Tamarai bush should open.

**Desktop:**
 - OS: Windows 10
 - Nvidia RTX 2080

**Comment by ZinaDerudder** [comment]
Sould has been fixed with the latest small update patch
