### ISSUE TITLE
Poison invisible walls when using life spell

### ISSUE THREAD

**Issue by Feelzor** [FishingCactus/NanotaleEarlyAccessBugs#131]
**Describe the bug**
When using the life spell to break down a poison wall (represented by the poison bubbles on the ground), the wall stays a little too long. If you run directly into it, the texture may disappear (or be extremely small) and you're still blocked for half a second.

**To Reproduce**
1. Go somewhere there are poison walls
2. Use life spell to break it
3. Immediatly sprint towards it

**Expected behavior**
As the poison is deleted, the wall should be removed and we should be able to pass through it freely

**Desktop:**
 - OS: Windows 10
 - Nvidia RTX 2080

**Comment by ZinaDerudder** [comment]
**Info for team**
The "poison wall" collider should be removed as soon as it has been hit by "life" spell.
**NOTE**
Visually, the collider is disabled as soon as the poison bubbles completely dissapear. It makes sense.
Decision up to you.
