### ISSUE TITLE
World loading screen renders the game irresponsive

### ISSUE THREAD

**Issue by Feelzor** [FishingCactus/NanotaleEarlyAccessBugs#132]
**Describe the bug**
When going from the outside to the sunken caves, there is a combination of events that seems to render the game irresponsive. The game will load sunken caves, then immediately loads the outside again but our character is still in the sunken caves. Follows a huge drop in fps (no more than 5 fps), escape menu is almost unreachable (it closes ~1 second after being shown) and everything is being slow.

**To Reproduce**
1. Go to sunken caves
2. Go back to the outside
3. Go to the sunken caves
4. During the loading screen, before the loading bar reaches the end, press the forward key (bound to Z in my case)
5. Keep the forward key pressed until the loading is completed.
6. A new loading screen should show. Wait for it to complete (it usually is a lot longer than the first one)

**Expected behavior**
Even with the forward key pressed, the game should load the sunken caves correctly.

**Screenshots**
https://youtu.be/6VkvSNNn4Ag

**Desktop:**
 - OS: Windows 10
 - Nvidia RTX 2080

**Comment by ZinaDerudder** [comment]
Might have been fixed with the latest small update patch
