### ISSUE TITLE
"Bridge created" animation replaying every time the camera goes out and in

### ISSUE THREAD

**Issue by Feelzor** [FishingCactus/NanotaleEarlyAccessBugs#136]
**Describe the bug**
Every time the camera hides this bridge and comes back to it, the animation of "unlocking a new bride" plays (see video).

**To Reproduce**
1. Go where this bridge is
2. Unlock it
3. Get it out of the camera (get far away to be sure it happens)
4. Come back

**Expected behavior**
As the bridge was previously unlocked, the animation shouldn't play.

**Screenshots**
https://youtu.be/K0UsUyOa6fg

**Desktop:**
 - OS: Windows 10
 - Nvidia RTX 2080

**Comment by ZinaDerudder** [comment]
Fixed
