### ISSUE TITLE
Keyboard mapping

### ISSUE THREAD

**Issue by Thornr** [FishingCactus/NanotaleEarlyAccessBugs#138]
Unable to map left shift key to sprint in keyboard mapping

**To Reproduce**
1. Go to 'Options' 
2. Press 'change key'
3. Nothing changes

**Desktop (please complete the following information):**
 -Windows 10
 - GTX970

**Comment by ZinaDerudder** [comment]
**Info for team**
SHIFT is normally the default keybinding for sprint. But SHIFT cannot be bind, indeed.
**Reproducing steps**
- options
- modify sprint keybinding
- try to modify sprint keybinding again, assigning "SHIFT"
- notice you cannot assign "SHIFT" for sprint.

**Comment by Ruvah** [comment]
fixed internally

**Comment by ZinaDerudder** [comment]
Fixed
