### ISSUE TITLE
Enemies not dying from FIRE after finishing the forest

### ISSUE THREAD

**Issue by mxrowan** [FishingCactus/NanotaleEarlyAccessBugs#139]
**Describe the bug:** After beating the Queen, exploring the forest again, I am trying to kill the early stationary enemies who you have to cast fire on to counter their healing. The enemies' healthbar turns red and it begins to take damage, but then it stops and health won't go down any further. 

The enemy doesn't appear to attack/aggro me anymore, although it continues its idle animations and most of them can still be targeted with any spell, though no damage is displayed. It may be that the game knows it's dead but has an issue in displaying that. One of the enemies additionally disappeared from targeting (doesn't display any word to target it with).

**To Reproduce** 
    After beating the queen, go to the area South-East of the Village, the first area that had these stationary enemies (though it seemed to also happen anywhere else with them).
    Cast any "Fire" spell on one
    See error

**Expected behavior** I thought they would die.

**Screenshots** If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/59551242/81508925-19659b00-92d5-11ea-8950-77b1bdef127d.png)
The south enemy (untargetable) was the first one I struck & noticed this issue with. I then tried the others with a FIRE + LARGE spell, which hit them all correctly but produced the same result.

![image](https://user-images.githubusercontent.com/59551242/81508961-4f0a8400-92d5-11ea-95c4-15f5145b6990.png)
map of where I am

**Desktop** (please complete the following information):

OS: Windows 10
NVIDIA GeForce GTX 1650 with Max-Q Design

**Additional context** The issue wasn't occurring on this run before beating the queen. I had played the game through twice prior to the sunken caves update (in January and in April) and didn't encounter this issue either time. Thanks so much for a great game!

Edit: reloading the game solved the issue for now!

**Comment by mxrowan** [comment]
Update: just happened again with a different (non-stationary) enemy. In this case it happened before using the FIRE spell, just targeting it normally caused it to stick at about half health, then casting FIRE once lowered it further but didn't kill it, and after that no other spells did any damage (as above).

Respawning did not solve the issue, though going to the main menu and reloading the save did.

![image](https://user-images.githubusercontent.com/59551242/81509607-ce9a5200-92d9-11ea-8f1a-b77398b2402f.png)

**Comment by ZinaDerudder** [comment]
Cannot reproduce, this should have been fixed.
@mxrowan If you are facing this issue again, please let me know
