### ISSUE TITLE
First combat after seeing with not spawning enemies

### ISSUE THREAD

**Issue by Feelzor** [FishingCactus/NanotaleEarlyAccessBugs#142]
**Describe the bug**
When doing the first combat after meeting the queen for the first time, the combat didn't spawn any enemies once the message was "Survive for 30 seconds", or something around 30 seconds left.

**To Reproduce**
1. Go to the fight
2. Survive until the message show "Survive for x seconds"
3. Try to wipe all waves as fast as possible

**Expected behavior**
Monsters should spawn as long as the combat is ongoing

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Nvidia RTX 2080

**Comment by ZinaDerudder** [comment]
Fixed.
