### ISSUE TITLE
Un allié (Joie) barre la route et des murs invisibles empêchent de passer

### ISSUE THREAD

**Issue by tchess14** [FishingCactus/NanotaleEarlyAccessBugs#143]
**Describe the bug**
Quelques pas à droite de l'endroit où la reine est apparue pour conseiller de quitter la forêt, faisant apparaitre une notification pour la quête principale "démons intérieurs", le personnage "Joie" (qui vous conseille de parler de JASPE à un habitant du village) est au milieu du chemin. Ce dernier semble assez large pour passer mais il semble barré de part et d'autres (en dessus et en-dessous de Joie) par des murs invisibles, empêchant dès lors de passer.
Et comme le dernier point de passage est situé juste à côté, d'où l'on vient, l'option "réapparaitre" ne sert à rien et le personnage est définitivement bloqué.

**To Reproduce**
1. Regarder la copie-écran.
2. Aller au lieu dit, voir la Reine puis explorer la zone située à gauche (au sud-ouest) pour récupérer le 3e fragment du sort de chaleur et revenir enfin sur ses pas.
3. Si Joie s'est déplacé comme sur l'image, il ne devrait pas être possible de le dépasser et d'aller vers la droite.

**Expected behavior**
Pouvoir marcher librement.

**Screenshots**
https://imgur.com/a/AYZHjC7

**Desktop (please complete the following information):**
 - OS: Windows 10]
 - Nvidia GeForce 1060

**Comment by tchess14** [comment]
J'ai finalement pu me débloquer en constatant que j'avais désormais "feu" et que je pouvais bruler des branches plus à l'ouest qui m'obstruaient le chemin. Ce qui me donne l'impression que placer Joie à cet endroit n'était pas un bug mais était volontaire empêche le joueur de repartir vers l'Est et l'obliger à aller vers l'ouest. Mais si c'est vraiment le cas, il faudrait vous y prendre autrement, car ça ressemble franchement à un bug et je n'ai pas été loin d'arrêter ma partie.

**Comment by VirginRedemption** [comment]
Oui ce n'est pas un bug. Mais le personnage est supposé vous dire qu'on ne peut pas passer. Je vais vérifier si le dialogue est toujours là. Merci.

**Comment by ZinaDerudder** [comment]
Fixed. Automatic dialog is triggered now.
