### ISSUE TITLE
Le journal des quêtes (sur la carte) est bloqué

### ISSUE THREAD

**Issue by tchess14** [FishingCactus/NanotaleEarlyAccessBugs#144]
**Describe the bug**
Sur la copie-écran disponible plus bas, on constate que la quête est "parler à la reine". Or, cela fait bien longtemps que j'ai parlé à la reine ; je l'ai même combattue (l'objectif à remplir lors de ce combat n'est d'ailleurs pas très clair) et j'ai aussi délivré l'arbre de vie de sa corruption. J'ai donc l'impression que la quête apparaissant sur la carte est bloquée.
Pour information, j'ai dans le jeu des messages de quêtes secondaires, mais aucune mention écrite n'apparait non plus sur l'écran de la carte (vu le bug mentionné plus haut, j'ignore si c'est normal). Par contre, sur la carte, j'ai bien les icônes des quêtes (mais parfois en double exemplaire comme on le voit au sud-ouest de la carte sur la copie-écran).

**To Reproduce**
??? aucune idée. L'objectif changeait correctement au début du jeu et s'est soudainement bloqué sans que je sache précisément quand (c'était de façon certaine avant de rencontrer l'ermite).

**Expected behavior**
Que les objectifs soient à jour et que je sache donc quelle est la quête principale. Savoir quelles sont les quêtes secondaires serait également agréable.

**Screenshots**
https://imgur.com/55U4pzk

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Nvidia GeForce 1060

**Comment by tchess14** [comment]
Pour information, j'ai désinstallé le jeu et recommencé une partie.

Cette fois-ci, la quête principale apparaissant sur la carte s'est bloquée encore plus tôt, puisque celle qui apparait est "nouvelle aube" (dirigez-vous vers de nouveaux horizons) avec comme objectif apparent et rempli (et donc coché) "suivez la boule de feu azure", alors que j'ai sauvé le renard et que son esprit vulpin m'a conduit dans la forêt. Bref, comme pour ma partie précédente, la quête principale n'est pas mise à jour sur la carte.

S'agissant des icônes de quête sur la carte (au point où j'en suis, "joyau de la foret" et "explosion de magie") elles apparaissent bien, mais ne disparaissent pas une fois l'item trouvé (en l'occurrence, j'ai trouvé le 1er fragment de la magie de poussée mais l'icône de quête est toujours présente). C'était déjà le cas lors de ma précédente partie.

Reste à voir si les icônes de savoir seront cette fois-ci correctes : lors de ma précédentes parties, plein d'icônes de savoir figuraient sur le territoire alors qu'il n'y avait (plus) rien à découvrir (au sud de la carte, là où l'on trouve plein de jaspes vertes : on le voit très bien sur la copie-écran, plus haut dans le 1er post).

**Comment by VirginRedemption** [comment]
Meric pour le rapport de bug. C'est noté et ça sera fixé pour la prochaine update.
