### ISSUE TITLE
Hardlocked when the first enemy is killed before approaching Master Lavender

### ISSUE THREAD

**Issue by Nestastnikos** [FishingCactus/NanotaleEarlyAccessBugs#146]
**Describe the bug**
When the Rosalind approaches Master Lavender in the part where Rosalind should kill her's first enemy, it is possible to attack enemy before the event is triggered. After that the player is hardlocked, it is not possible to continue due to blocking invisible wall.

**To Reproduce**
1. Precondition: Rosalind is in the "tutorial" part where she should encounter her first enemy.
2. Precondition: The dialogue with Master Lavender has not triggered yet.
3. Precondition: The enemy is still alive.
4. Precondition: Rosalind has enemy in range (sees the word above the enemy when in type mode).
5. Kill the enemy.
6. Walk with Rosalind to the place, where the Lavender was standing.

**Actual behavior**
There is invisible wall preventing player from continuing.

**Expected behavior**
The player should be able to advance to the next part of the game.

**Screenshots**
https://media.giphy.com/media/VgB0PataC5Oy9gOjyK/giphy.gif

**Comment by ZinaDerudder** [comment]
Fixed
