### ISSUE TITLE
Softlocked state after the dialogue is exited with ESC

### ISSUE THREAD

**Issue by Nestastnikos** [FishingCactus/NanotaleEarlyAccessBugs#147]
**Describe the bug**
When the conversation is interrupted by navigating to in-game menu (pressing ESC on keyboard), the game starts to have weird behavior - the Rosalind has weird movement animation, the Rosalind cannot interact with the characters etc.

**To Reproduce**
1. Enter the dialogue (eg with Master Lavender).
2. Press <ESC> to open in-game menu.
3. Close the ingame menu.
4. (Optional step - see _Additional context_) If  the Rosalind is still in dialogue, repeat the process from step 2.

**Actual behavior**
The dialogue is closed and the game enters weird state.

**Expected behavior**
The Rosalind should stay in the dialogue.

**Screenshots**
https://media.giphy.com/media/gf5UHBMa88j81JljmG/giphy.gif

![Screenshot_13 - Copy](https://user-images.githubusercontent.com/23109654/82737997-00c59e00-9d35-11ea-8678-1bc5ef1e10ec.png)
- the story does not progress after the game has entered that weird state

**Additional context**
It may require a little bit effort to reproduce this, I could reproduce it in any state of the dialogue (beginning, end), it does not matter. I also tried to reproduce this with the Queen and I was successful. In order to reproduce it you may need to try the repro steps several times (I needed at most 3).

The game cannot be fixed by going to main menu and starting from the beginning. The weird state persists even if the story is started from another profile. The only way (which I've found so far) was to restart the game.

**Comment by ZinaDerudder** [comment]
Fixed in altest update
