### ISSUE TITLE
Burning Rosalind when not surrounded by fire

### ISSUE THREAD

**Issue by Nestastnikos** [FishingCactus/NanotaleEarlyAccessBugs#148]
**Describe the bug**
When the Rosalind stands in the grass which burns, she starts to burn as well (which is normal). The problem is that she starts to burn too early, even if she is not surrounded by fire.

**To Reproduce**
1. Find the grass which can be burnt by explosive plant.
2. Enter the grass with Rosalind (but far away from the explosive plant).
3. Enter type mode.
4. Destroy the explosive plant.
5. Stay in the grass.

**Actual behavior**
The Rosalind starts to burn almost immediately after the plant exploded.

**Expected behavior**
The Rosalind should start to burn when the fire reaches her (or is very close by).

**Screenshots**
![example-gif](https://media.giphy.com/media/jSEfNc0qsOq045PSFf/giphy.gif)

**Comment by ZinaDerudder** [comment]
Should be fixed.
@Nestastnikos if you are still facing this issue, please let me know =)
