### ISSUE TITLE
Hermit missing?

### ISSUE THREAD

**Issue by Graewynd** [FishingCactus/NanotaleEarlyAccessBugs#155]
Version 0.5.7433.29811.EA-r
I completed the Queen/Tree of Life before going into the area where the Hermit should be.  When I went there afterwards, the Hermit was gone, even though the map still showed there should be some lore there.  Is the Hermit supposed to disappear after the Tree is saved?

**Comment by ZinaDerudder** [comment]
Hi @Graewynd 
Can you send me a screenshot of the spot you were to meet the Hermit? (map or in-game visual, both are ok).
Thanks in advance =)

**Comment by Graewynd** [comment]
Where I am standing is where I thought the Hermit should be, from previous run-throughs.  If I'm mistaken, and the Hermit is actually to the East where it says "Hermit" and I can't get to yet, then I apologize for the confusion.  I thought I remember having a conversation where I am standing.
![image](https://user-images.githubusercontent.com/57119636/84821949-f02dde00-afe9-11ea-8cdd-6d0d04661558.png)
