### ISSUE TITLE
Things in Forest messed up after returning from caves

### ISSUE THREAD

**Issue by Graewynd** [FishingCactus/NanotaleEarlyAccessBugs#156]
Version 0.5.7433.29811.EA-r
After being in the caves, I returned to the Forest (didn't mean to, but that's not the point).
Got the black screen that has been reported in Steam and used Respawn to get the graphics back.
However, all the "lore" symbols on the map reappeared, all the enemies were back, but didn't seem aggressive, some of the sheep were shaking back and forth (and back to blocking paths).
Seems to me that things should be saved the way they were when the Forest was left and restored to their correct state upon return to the Forest.

**Comment by ZinaDerudder** [comment]
Should be fixed.
@Graewynd if you are still facing those issues, please let me know.
