### ISSUE TITLE
French language: FEUILLES/FEU + Coeur

### ISSUE THREAD

**Issue by vicrabb** [FishingCactus/NanotaleEarlyAccessBugs#158]
Hello,

I've two issues with the French:

1) I've a tree with the word feuilles to write. However, I can't because it's the fire spell that is each time spelled: feu. The game is resetting the spelling after spelling feu. It means that I can't add it to the encyclopedia, unless there is something new that I missed.

![20200617123845_1](https://user-images.githubusercontent.com/34101794/84889200-c67fc000-b098-11ea-9eb9-dfdb8415d291.jpg)

2) Word coeur is spelled cœur. However, I had to search through the web how to spell it with the keyboard. Perhaps it would be useful to have a sort of cheatsheet in the game for special characters that need a combinaison like ALT+0156 to be spelled or even a spell that would used that or a quest learning you to do it.

Thanks!

**Comment by ZinaDerudder** [comment]
Thanks for your report. We're gonna fix that = )
