### ISSUE TITLE
Reloading issues after battle arena death (first carrier arena)

### ISSUE THREAD

**Issue by brunourbain** [FishingCactus/NanotaleEarlyAccessBugs#16]
**Describe the bug**
During the first carrier arena, health reached zero. However, instead of reloading,  the player avatar disappeared and the timer for the wave continued to count down. When the timer reached zero, the screen got shunted and a "+500 experience" text appeared. Could move around and enter typing mode, but the avatar was invisible. I exited and rebooted the game. On reloading, the same issues (invisible avatar, no words appearing) were still there, as well as the camera uncontrollable zooming in/out.

Similar cases are reported 

**To Reproduce**
Die in a Battle Arena
The avatar doesn't come back to life or there are issues reloading the last save position.
Seems to happen more when you are close to winning the battle or just when you won the battle.

**Expected behavior**
Restore the previous save location and reset properly the

**Comment by kantra19** [comment]
This happened to me about 20 minutes ago. I was on the arena near the backpack-looking stone. After the battle ended and my camera went to my character, I couldn't move off the screen the character was in because I think the camera broke. Reloading didn't fix the issue.

**Comment by ZinaDerudder** [comment]
This issue should be fixed in the current Steam version.
Battle is now working, and camera resets correctly after death or win.
