### ISSUE TITLE
Not discovered enemies during the gameplay

### ISSUE THREAD

**Issue by Nestastnikos** [FishingCactus/NanotaleEarlyAccessBugs#165]
**Describe the bug**
After I completed the whole game, none of the enemies were shown in the encyclopedia.

**Expected behavior**
There should be some notes from encountered enemies.

**Screenshots**
![Screenshot_30](https://user-images.githubusercontent.com/23109654/85746487-c752ca80-b706-11ea-9b32-0975cfd6aebc.png)

**Comment by Ruvah** [comment]
collecting enemy lore is not live yet, but it will come available in the coming update
