### ISSUE TITLE
Newline (enter) counted as character during new profile creation process

### ISSUE THREAD

**Issue by Nestastnikos** [FishingCactus/NanotaleEarlyAccessBugs#172]
**Describe the bug**
Simple enter is counted as valid character for profile, during the creation of new profile for the player.

**To Reproduce**
1. Precondition: Game is launched in main menu.
2. Navigate to New Game
3. Press Enter

**Actual behavior**
The Enter (newline) is counted as character.

**Expected behavior**
No action should be performed.

**Screenshots**
![20200630181720_1](https://user-images.githubusercontent.com/23109654/86150668-fe0d5400-bafd-11ea-908a-b6b014dc336a.jpg)

**Comment by Ruvah** [comment]
Enter should start the game instead adding a newline to the save name, as intended
