### ISSUE TITLE
Key bindings do not save

### ISSUE THREAD

**Issue by svatoupravdu** [FishingCactus/NanotaleEarlyAccessBugs#174]
**Describe the bug**
When I redefine my keys, they stay redefined only for the gameplay session. After restarting the game those keys are back to default.

**To Reproduce**
1. Go to Options
2. Redefine some key from default to custom
3. Quit game
4. Start game
5. Go to Options
6. Observe the horror.

**Expected behavior**
Redefined keys should stay redefined

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
c:\Users\user\AppData\LocalLow\Fishing Cactus\Nanotale\  files are writable but I don't know if it's the location of config files.

**Comment by Thornr** [comment]
I'm having the same issue.
