### ISSUE TITLE
Sinking into water

### ISSUE THREAD

**Issue by MewMewMew007** [FishingCactus/NanotaleEarlyAccessBugs#176]
If you are standing on ice, and the ice melts from fire, you will sink down into the water.

**To Reproduce**
1. Go to any pool of water that can be affected by ice.
2. Make ice and stand on it, and then melt it.
3. See error

**Expected behavior**
I didn't think that it would sink me into the water.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - I don't know, I'm on a gaming laptop.

**Additional context**
This forces you to hit the respawn button, as there is no way to get out.  Ice will form above your head if you try to get out that way.
![bug](https://user-images.githubusercontent.com/68441355/87817742-7e8abf00-c837-11ea-851d-55973b4f215c.png)

**Comment by ZinaDerudder** [comment]
Hello MewMewMew007
This should not occur anymore. If Rosalind is falling into water, she should teleport automatically to the ground.
