### ISSUE TITLE
Camera's position is changed after first blue plant

### ISSUE THREAD

**Issue by TutyninVladimir** [FishingCactus/NanotaleEarlyAccessBugs#19]
1) I started game;
2) Activated water plant (completed minigame with 5 words);
3) After that camera's position was as on screenshots (too close to character);
4) Camera's position was changed in dialogs, but return in close position;
5) It was repaired after returning main menu.
6) In next time bug not repeated (mb because I can't start game, only continue it :) )

![20191024204508_1](https://user-images.githubusercontent.com/17814161/67513914-7e90d080-f6a4-11e9-9282-911709489684.jpg)
![20191024204517_1](https://user-images.githubusercontent.com/17814161/67513916-7f296700-f6a4-11e9-81fb-7e51eadf5496.jpg)
![20191024204947_1](https://user-images.githubusercontent.com/17814161/67513917-7fc1fd80-f6a4-11e9-818d-907c90923125.jpg)

Windows 8.1, Resolution 1366x768, Videocard NVidia GeForce GT 740M

**Comment by ZachHaber** [comment]
I've noticed that this occurs whenever you have one of those word minigames, it changes the camera as the minigame starts, and doesn't reset it after. Hope this helps!

**Comment by grumiauxl** [comment]
Fixed in Steam build 4325120
