### ISSUE TITLE
Two buttons "BACK" in "Options"

### ISSUE THREAD

**Issue by TutyninVladimir** [FishingCactus/NanotaleEarlyAccessBugs#20]
In options I have got two buttons "BACK".

![20191024210056_1](https://user-images.githubusercontent.com/17814161/67514089-ca437a00-f6a4-11e9-80bb-b0792c4d42af.jpg)

Windows 8.1, Resolution 1366x768.

**Comment by grumiauxl** [comment]
Fixed in Steam build 4325120
