### ISSUE TITLE
Invisible wall by flower, can't type to discover

### ISSUE THREAD

**Issue by kantra19** [FishingCactus/NanotaleEarlyAccessBugs#22]
![20191024185339_1](https://user-images.githubusercontent.com/56983552/67532622-eccd9700-f694-11e9-81a2-d1623776a710.jpg)
![20191024185313_1](https://user-images.githubusercontent.com/56983552/67532666-171f5480-f695-11e9-959f-9f3134348a31.jpg)

There's still an invisible wall here where I'm standing, so I can't get to the flower. In typing mode, the text doesn't show up.  (Uploaded map for reference)

**Comment by brunourbain** [comment]
Hello Kantra, for this one you need to climb the small ramp at your right, next to the rocks. Just tested it works fine.
