### ISSUE TITLE
Couldn't discover this green jasper

### ISSUE THREAD

**Issue by kantra19** [FishingCactus/NanotaleEarlyAccessBugs#23]
![20191024190250_1](https://user-images.githubusercontent.com/56983552/67532715-4f269780-f695-11e9-8bca-48448234ba7f.jpg)
![20191024190300_1](https://user-images.githubusercontent.com/56983552/67532720-53eb4b80-f695-11e9-8638-5be78d30311d.jpg)

Located here on the map. It's near the seated NPC, but still. It did follow me for a bit, but it's supposed to be discoverable and I couldn't do it.

**Comment by brunourbain** [comment]
Yeah there are a couple of issues with the Jasper. Thanks for the report, we'll see if we can find the cause of it.

**Comment by ZinaDerudder** [comment]
This little monster can now be analysed.
