### ISSUE TITLE
Start the game/reloaded, can't enter typing mode

### ISSUE THREAD

**Issue by kantra19** [FishingCactus/NanotaleEarlyAccessBugs#24]
A bit self-explanatory. The first time I started the game, then wanted to restart the game from the beginning to see what the update had changed, but I couldn't (and still can't) find an option to restart the game from the beginning, so I just reloaded. I came back in and couldn't get into keyboard mode. Was fixed by quitting out entirely and restarting the game. It happened later after I "died" in an arena and had to reload to fix the camera.

**Comment by brunourbain** [comment]
Right now there is no way to reset your save file except deleting the fil itself which is located in your AppData folder. Will ask the team if that's a possible options.

**Comment by brunourbain** [comment]
The issue encountered before restarting is probably because of a corrupted dialog tree.

**Comment by ZinaDerudder** [comment]
This issue is known. Should be fixed soon.

**Comment by ZinaDerudder** [comment]
Hello @kantra19 
First, thank you for helping us, it's really much appreciated =)
In the current Steam build (pushed on Steam on 5th November), you are able to get back to the main menu, resuming to game, and entering typing mode.
