### ISSUE TITLE
Game doesn't pause when map is open or level up happens

### ISSUE THREAD

**Issue by kantra19** [FishingCactus/NanotaleEarlyAccessBugs#28]
**Describe the bug**
When you open the map or level up, the game isn't "paused", e.g., monsters can still detect you and walk around, even though you're frozen. And when you level up, you're not given the option to quit out of the window, so you have to wait for it to load (unlike when you're looking at the map and can just quit out). So I leveled up while stepping towards an enemy. I was frozen in place during the level up screen, and an enemy approached me and hit me three times before the skill up window finished loading, I selected a skill, and the window went away and unfroze me.

**To Reproduce**
1. Level up while stepping towards an enemy
2. The enemy eats your face while you're frozen in place, waiting for the very slow skill menu to load so you can select something and make it go away.

**Expected behavior**
At least while leveling up, the game should pause. Enemies should not still be able to detect you, advance towards you, or attack you, or at least freeze until you've finished the level up and you are unfrozen.

**Comment by ZinaDerudder** [comment]
The game is now under pause state when navigating in the menu, or when a Level Up pop-up is displayed. No risk of being attacked by an enemy anymore.
