### ISSUE TITLE
Game crashed while playing in french language

### ISSUE THREAD

**Issue by Inorinuki** [FishingCactus/NanotaleEarlyAccessBugs#30]
**Describe the bug**
First of all, I'm living in France, and use an Azerty keyboard.
I started the game without changing any options (when I looked in the options, the game was in french, with "esdf" keyboard). At the very beginning, before even moving the character, when the game asked me to type the third word in french "forêt" ("forest" in english), the game crashed while typing the "f" and shutted down itself. 
It seems that the translation in french caused the game to crash, because when I changed the options to force the game to be in english (and choose "zqsd" keyboard, but I don't think that this option is part of the issue), I can go through and continue the game.

**To Reproduce**
1. Start the game without changing any options (game was in french, with "esdf" keyboard).
2. Fail to type the third word, "forêt".
3. Game crash and shut down.

**Expected behavior**
The game should not crash.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Nvidia GeForce GTX 1060 3GB

**Comment by brunourbain** [comment]
Bonjour peux-tu clarifier "fail" d'écrire forêt ? (il s'agit bien de la combinaison de ^ et de e).

Donc le jeu a été par défaut en FR (je suppose que tu as ton steam en FR aussi?).

On va investiguer c'est peut etre une mauvaise paramétrisation au départ lorsque le jeu est set par défaut en FR car si tu commences en Anglais, change pour le FR (avec un restart) alors ca fonctionne correctement.
