### ISSUE TITLE
Black Gates not going away after arena fights

### ISSUE THREAD

**Issue by xNightAngelx** [FishingCactus/NanotaleEarlyAccessBugs#31]
**Describe the bug**
There are black gates appearing when arena fights start. They disappear when the arena fights finish. However, they reappear when the game gets reloaded or even using the 'respawn' option for whatever reason. I had to respawn at the third arena fight (not including tuturial) because I couldn't talk to the queen properly after beating her. After I respawned, I was outside of the black gate (see screenshots).

**To Reproduce**
1. Beat the second/third arena fight.
2. Quit the game completely or respawn or quit to menu.
3. Get back into the game.
4. See black gate appearing.

**Expected behavior**

**Screenshots**
![20191025212742_1](https://user-images.githubusercontent.com/56989020/67613555-c7b45380-f77c-11e9-904a-ae485e94575f.jpg)
![20191025224807_1](https://user-images.githubusercontent.com/56989020/67613558-caaf4400-f77c-11e9-8e14-0bc2599a6f69.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - geforce gtx 1070

**Additional context**

**Comment by ZinaDerudder** [comment]
Hello @xNightAngelx 
Thank you for repporting that bug =)
It is now fixed in the current Steam version (pushed on Steam on 5th November).
