### ISSUE TITLE
game blocked how restart from clean new start ?

### ISSUE THREAD

**Issue by jhonphilipps** [FishingCactus/NanotaleEarlyAccessBugs#32]
**Describe the bug**
after a big fight with water mob and fire mob the game stuck in place, roselin book in hand and blocked on place ... i leave to the menu and type "commencer" now roslin back at start game all unlocked and blocked

**To Reproduce**
play the game and when you stuck just leave to menu and type "commencer" to block the game 🗡 

**Expected behavior**
what's the plan about autosaved game how recover it, how restart a new game and erase it?

**Comment by brunourbain** [comment]
You can erase the save file in your AppData folder. 

You can also use the Respawn button in the options menu.

Commencer doesn't reset the game, it normally resumes it (unless you have no save yet).

**Comment by ZinaDerudder** [comment]
Hello @jhonphilipps 
Thanks for helping with the bug report =)
This should be fixed in the current Steam version (pushed on Steam on 5th November).
