### ISSUE TITLE
menu encyclo french, game crash quit 

### ISSUE THREAD

**Issue by jhonphilipps** [FishingCactus/NanotaleEarlyAccessBugs#33]
**Describe the bug**
game crash with encyclopedia after try many space bar

**To Reproduce**
1. Go to 'encyclopedia'
2. Press 'many time space bar when trying to type some words on plants'
3. game crash quit , desktop return.

**Comment by ZinaDerudder** [comment]
Hello @jhonphilipps 
The Encyclopedia is indeed currently not working.
We'll fix that as soon as possible.

**Comment by ZinaDerudder** [comment]
Tried to reproduce, and didn't manage to make it crash.
I suppose your crash was possibly due to something else.
If you face that again, let me know.
