### ISSUE TITLE
Missing salligush?

### ISSUE THREAD

**Issue by kantra19** [FishingCactus/NanotaleEarlyAccessBugs#35]
**Describe the bug**
I think there's a missing salligush. I've activated all the ones in the area and can't figure out how to make the section to Rosalind's left grow.

**Screenshots**
![20191026105855_1](https://user-images.githubusercontent.com/56983552/67622040-f74a7680-f7e3-11e9-8f65-d519f3dba1c1.jpg)
![20191026105904_1](https://user-images.githubusercontent.com/56983552/67622041-fdd8ee00-f7e3-11e9-866b-29dd4e7fb4fc.jpg)

**Comment by ZinaDerudder** [comment]
@Kitwsien Can we add/move a salligush so that section's grass can also grow?

**Comment by ZinaDerudder** [comment]
After discussion, this section is meant to be like this.
