### ISSUE TITLE
Typings with spaces in them lose track of the input

### ISSUE THREAD

**Issue by Graewynd** [FishingCactus/NanotaleEarlyAccessBugs#36]
As an example, the upgrade "Increased damage on rat enemies", if "Increaseddamage" is typed (leaving out the space) the highlighting lags (the second "d" doesn't change until the 'a' is typed) and the lag increases for each space in the sentence.

**Comment by Graewynd** [comment]
Update #4 - better, but not perfect.  With the "Increased damage on rat enemy" line, I (think) I tried a space before "enemy", and it lagged one letter on the highlight, but then caught up on the next letter.

**Comment by ZinaDerudder** [comment]
Hello @Graewynd 
Thanks for reporting that =)
This is now fixed in the current Steam version (Pushed on 5th November).
