### ISSUE TITLE
Hermit issues

### ISSUE THREAD

**Issue by Graewynd** [FishingCactus/NanotaleEarlyAccessBugs#37]
In the dialogue with the Hermit, "Did you ever come across Heaven's ROOT...", the "T" can't be entered.  I was able to ESC to get out of the dialogue, but on subsequent attempts I reached a point where the dialogue stayed on the screen, and if typing mode was entered (space) the game softlocked and I had to use the Respawn.
![image](https://user-images.githubusercontent.com/57119636/67734599-d6e30d80-f9d7-11e9-97ac-c80fbe0af452.png)
Example of dialogue "trailing" the Rosalind (walking to left away from Hermit):
![image](https://user-images.githubusercontent.com/57119636/67734668-072aac00-f9d8-11e9-9b50-0a166cd7a2db.png)

**Comment by ZinaDerudder** [comment]
Hello @Graewynd 
This bug is now fixed on the current Steam version (verified on the 5th November).
