### ISSUE TITLE
Can't access flower with lore

### ISSUE THREAD

**Issue by Graewynd** [FishingCactus/NanotaleEarlyAccessBugs#38]
To the right of hermit there is a flower at the far end of a bridge that appears to be one that should have lore, but I don't get any word to type no matter how I try to approach it.  Here is the picture:
![image](https://user-images.githubusercontent.com/57119636/67734791-6dafca00-f9d8-11e9-99d8-e223835ba0c5.png)

**Comment by kantra19** [comment]
![20191029190904_1](https://user-images.githubusercontent.com/56983552/67816710-35b09180-fa81-11e9-830f-a90071c3d647.jpg)
Having the same problem after the update. Here's a screencap of where it is on the map.

**Comment by ZinaDerudder** [comment]
Thanks for reporting that, we'll fix that issue.

**Comment by ZinaDerudder** [comment]
Fixed. the flower can now be analyzed
