### ISSUE TITLE
Can't access Green Jasper with lore

### ISSUE THREAD

**Issue by Graewynd** [FishingCactus/NanotaleEarlyAccessBugs#39]
There is a Green Jasper that would not give lore (or experience?).  I was in the fog (to the southwest of the picture) and went into typing mode, got the word ATTACK, but after completing it nothing happened and I could not get any response after that, until I opened the bridge, then when I went into typing mode I got the W that is seen in the picture, but there was no response to that W. Including a partial snapshot of the map to show where it is located.
![image](https://user-images.githubusercontent.com/57119636/67735534-d13af700-f9da-11e9-9fce-0d5a3914e943.png)
![image](https://user-images.githubusercontent.com/57119636/67735540-d6984180-f9da-11e9-9207-a09eb4a235fe.png)

**Comment by kantra19** [comment]
Still having the same problem after the update. I can't learn any of the various Jasper here.

**Comment by Spreekatze** [comment]
Run into the same bug. Could type some jasper words, but didnt got anything for it, nor did the visual change that tells me, that there is a word to be typed. One now has that "w", others dont have any words, but still the circle around them.

**Comment by Graewynd** [comment]
Green Jasper issues seem to mostly be fixed in Update #5. Closing this.
