### ISSUE TITLE
Bridges Crossing / re-crossing issues

### ISSUE THREAD

**Issue by grumiauxl** [FishingCactus/NanotaleEarlyAccessBugs#4]
There are some collision bugs on magical bridges which make it hard sometimes to back track on them after you have crossed them.

If it also possible to fall off from the bridges and in rare occasions, get stuck in the environment.

**Comment by kantra19** [comment]
![20191024185901_1](https://user-images.githubusercontent.com/56983552/67532546-9eb89380-f694-11e9-8a93-03b24a46cc61.jpg)
Still can't backtrack over this bridge.

**Comment by grumiauxl** [comment]
Thanks for the report, we are trying to fix all remaining bridge issues today and will push a fix ASAP
