### ISSUE TITLE
Couldn't figure out how to advance on NPC's text bubble - had to guess, their text bubble frozen

### ISSUE THREAD

**Issue by kantra19** [FishingCactus/NanotaleEarlyAccessBugs#40]
**Describe the bug**
No text appeared for me to type for this speech bubble (right before what's on the screen, not JASPER; I didn't screencap it before I randomly lucked out on what worked), or any spacebar to advance, and the text bubble didn't time out. I had to guess what to type, and after I typed something that got it to work, the speech bubble was frozen to the screen. I had to respawn, which broke my walk cycle.

![20191029190428_1](https://user-images.githubusercontent.com/56983552/67816842-a2c42700-fa81-11e9-9856-0ede44d06521.jpg)
![20191029190439_1](https://user-images.githubusercontent.com/56983552/67816847-a48dea80-fa81-11e9-84fb-cac6da296512.jpg)

**Comment by ZinaDerudder** [comment]
This is now fixed: you have clearer idea of what needs to be typed.
