### ISSUE TITLE
Can get damaged while Level Up window is active

### ISSUE THREAD

**Issue by Graewynd** [FishingCactus/NanotaleEarlyAccessBugs#41]
I had a situation where the Level Up stage occurred, but I was near creatures that kept advancing and damaging me while trying to decide which perk to take.  I didn't die, but it was close.  It seems to me that the game play should be frozen when leveling up, as there is no control over when that occurs.

This was not with the patch referred to in Update #4, so sorry if this has been fixed already.

**Comment by ZinaDerudder** [comment]
Hi.
This is not occuring anymore: as soon as you are navigating in the menu, or when a level-up pop up is displayed, the game is paused: you cannot be attacked by enemies anymore.
