### ISSUE TITLE
Banner should update when changing control scheme

### ISSUE THREAD

**Issue by jruderman** [FishingCactus/NanotaleEarlyAccessBugs#42]
1. Start the game from the beginning
2. Go through dialogue until a "move with ESDF" banner appears
3. Go to options and change to WASD controls
4. Close the menu to return to game word

Result: banner still says "move with ESDF"

Expected: banner should now say "move with WASD"

**Comment by ZinaDerudder** [comment]
Hello jruderman.
Thank for reporting that, we'll adapt the banner according to the chosen keyboard controls.
