### ISSUE TITLE
Can't type apostrophe in plant name

### ISSUE THREAD

**Issue by jruderman** [FishingCactus/NanotaleEarlyAccessBugs#43]
1. Menu > Encyclopedia > Plants
2. Find the page with "Creeper's Brush"
3. Type "Creeper's Brush"

Result: the apostrophe I type is not recognized, so only "Creeper" is accepted

(Windows 10, everything set to English)

**Comment by VirginRedemption** [comment]
We are currently working on all the encyclopedia features and issues. Thank you for the report.

**Comment by ZinaDerudder** [comment]
Apostrophe can now be typed.
