### ISSUE TITLE
Colors change briefly on Alt+Tab

### ISSUE THREAD

**Issue by jruderman** [FishingCactus/NanotaleEarlyAccessBugs#44]
When I Alt+Tab to Steam, so that Steam appears in front of my full-screen game, orange plants briefly become purple. They go back to orange in under a second.

* OS: Windows 10 (64-bit)
* Graphics: AMD Radeon HD 7900 Series

**Comment by ZinaDerudder** [comment]
Hi Jruderman.
Can you send me a screenshot of the plants you're talking about? I'll try if I can reproduce it.
Also, can you tell me what graphic settings you have for Nanotale?
Thanks in advance =)
