### ISSUE TITLE
Typing when map up (ESC) also affects world

### ISSUE THREAD

**Issue by Graewynd** [FishingCactus/NanotaleEarlyAccessBugs#46]
Update #4. This is a variant on the issue when the Level Up dialogue appears.  When the map is up after pressing ESC, typing mode can be entered and underlying (and often unseen) objects in the world accept the typed letters and react.  I think this also led to a buggy situation.  I had the word "DETONATION" as shown below, but could not progress past the DET (the O wouldn't take), but if I typed the whole word then the first O clear when I reached the O in TION.  I tried multiple times, going in and out of typing mode.  Then I hit ESC, brought up the map, hit ESC again and now magically I could type the word.  The only thing I can think of is that I was on the map before approaching this area and was playing around with typing to see if I could get the Encyclopedia entries to do anything (couldn't, and Enter didn't seem to do anything).  I suspect there is some unintended affects of typing with the map up, and it seems to me that the underlying gameplay should be suspended when any dialogue is up.
![image](https://user-images.githubusercontent.com/57119636/67881045-26c7ee80-fb16-11e9-9e15-727dc79347da.png)

**Comment by Graewynd** [comment]
Issue still exists in Update #5, at least as far as typing with map up (if ESC is hit while in typing mode) continues to clear the words.  Hitting ESC should completely pause the underlying game.

**Comment by ZinaDerudder** [comment]
Typing being in the menu or in a level up pop-up is now impossible.
