### ISSUE TITLE
Fell off bridge and stuck

### ISSUE THREAD

**Issue by Graewynd** [FishingCactus/NanotaleEarlyAccessBugs#47]
Update #4. Somehow I fell off the bridge (see arrow) and got stuck behind the flower.  Had to respawn, and then couldn't recreate (had just killed the two creatures at the end of the bridge the first time.
![image](https://user-images.githubusercontent.com/57119636/67881570-182e0700-fb17-11e9-8c37-e7b7092e5b7f.png)
![image](https://user-images.githubusercontent.com/57119636/67881617-31cf4e80-fb17-11e9-898f-3db27af2c1cf.png)

**Comment by ZinaDerudder** [comment]
Hello @Graewynd 
Thank you for repporting this issue.
The collider has been modified, it should not be possible to fall drom the bridge anymore.
The fix will be there in the upcoming Steam update.
