### ISSUE TITLE
No response from "stone"?

### ISSUE THREAD

**Issue by Graewynd** [FishingCactus/NanotaleEarlyAccessBugs#48]
Update #4.  Also happened in previous update.  This entity accepted a word (CELEBRATED) but there was no reaction to it, and after that no additional word would appear, even though it still has the vertical lines indicating there should be lore/experience etc.  Note that I have not done the second battle, if that has any bearing (not counting the FOX semi-battle).
![image](https://user-images.githubusercontent.com/57119636/67888528-a6a88580-fb23-11e9-80e2-687e2ba567a2.png)
![image](https://user-images.githubusercontent.com/57119636/67888608-d061ac80-fb23-11e9-84cb-32e4cef6330d.png)

**Comment by Graewynd** [comment]
Found my way back here later on and this time it worked, giving part of the King story.

**Comment by grumiauxl** [comment]
Hi @Graewynd Sorry this happened, we fixed a bunch of issues related to missing lore, maybe that was one of them.
Thanks for your report, enjoy the game!
