### ISSUE TITLE
Continued Green Jasper issues Update #4

### ISSUE THREAD

**Issue by Graewynd** [FishingCactus/NanotaleEarlyAccessBugs#49]
See also #39, but after getting successfully through the Jasper by the bridge, when I uncountered the "flock" of Green Jaspers to the SW (at one time up to seven of them), they came up with words like MINT and ATTACK and JASPER, even though I'm sure at least the ATTACK and MINT were done with.  Again, there was no response to the words, and I softlocked in typing mode after a couple attempts.  Upon RESPAWN the camera was zoomed in pretty far and could not figure out how to get out of the zoom.  I had done an ESC and zoomed Out on the map to take a screenshot for the bug - don't know if that is related.  Had to completely exit the game and then start again to have the zoom issue resolve. Picture shows 5 Jaspers, but had seven before a couple ran away.
![image](https://user-images.githubusercontent.com/57119636/67891547-2be26900-fb29-11e9-9bf9-4c52fae52a83.png)
![image](https://user-images.githubusercontent.com/57119636/67891606-487ea100-fb29-11e9-9342-15c095845cc7.png)

**Comment by VirginRedemption** [comment]
Fixed
