### ISSUE TITLE
Another bridge issue, in Update #4

### ISSUE THREAD

**Issue by Graewynd** [FishingCactus/NanotaleEarlyAccessBugs#51]
I was able to get stuck off the left side of the bridge shown, and could do it multiple times after respawning, but only with a lot of luck - going left/right/up/down and sometimes into and out of typing mode.  Eventually I'd be stuck in one spot.
![image](https://user-images.githubusercontent.com/57119636/67904653-6954ef80-fb45-11e9-801c-f7d2c755762b.png)
![image](https://user-images.githubusercontent.com/57119636/67904694-88538180-fb45-11e9-89dd-dd99871a6ebc.png)

**Comment by InnoAnca** [comment]
fixed
