### ISSUE TITLE
Pretty confusing story progression

### ISSUE THREAD

**Issue by Graewynd** [FishingCactus/NanotaleEarlyAccessBugs#52]
I reached this group of folks before the Queen battle (had been asked to go talk to the queen by another character elsewhere), and they were asking me if "I did it" or the "Queen did it" and "Was the Queen always like this" and more, but I had no real context for understanding their concerns.  It was only after I went to the left and saw the "corrupted Queen" that things made a (little) more sense.  Suggest better story development needed.
![image](https://user-images.githubusercontent.com/57119636/67904858-0f085e80-fb46-11e9-8684-47146ff45b90.png)

**Comment by Graewynd** [comment]
I reiterate this suggestion after playing through again in Update #5.  All the dialogue with these characters make no sense unless one has already had the queen battle, or at least seen the corrupt queen.  In addition, after being asked to visit the queen, there is a place where movement is now blocked that seems illogical, as shown below.  It looks very obvious that Rosalind should be able to walk behind the fire and around the back of the character, but there is this "invisible wall" present preventing that.
![image](https://user-images.githubusercontent.com/57119636/68489446-1948ed80-0215-11ea-9280-b97f4754f0e4.png)

**Comment by VirginRedemption** [comment]
I reported your suggestion for the first part regarding the story before the Queen battle. 

For the second part, we put invisible blockers preventing backtracking during the early access. These "walls" will be removed at the final release, allowing you to unlock new areas in the forest and to reach the next biome.
