### ISSUE TITLE
All words from typable words set for particular dialogue can be typed during dialogue

### ISSUE THREAD

**Issue by Nestastnikos** [FishingCactus/NanotaleEarlyAccessBugs#59]
**Describe the bug**
When the dialogue is entered and the player should interact with the character by typing the uppercased words, all words are available during dialogue, not only those which are currently displayed on the screen.

**To Reproduce**
1. Precondition: The game has set gameplay language in Polish.
2. Precondition: Rosalind in dialogue with the character nearby tree of life.
3. Type "PA" (which is bye in english).

**Actual behavior**
All parts are skipped and dialogue ended (since I checked that this is the word that should be typed in case you want to end this particular dialogue).

**Expected behavior**
Nothing should happen.

**Screenshots**
![20191031221614_1](https://user-images.githubusercontent.com/23109654/68037120-566a2880-fcc7-11e9-9d3a-e31ff74b636b.jpg)

**Additional context**
Only the words "Ciężko" and "Drzewa" should be available at that time, but actually any word which is available for that particular dialogue can be typed and the bubble which should be triggered after that word is displayed. Even if you are inside the dialogue and you type again "Hi" or "Hello". the dialogue is restarted from the beginning.

**Comment by VirginRedemption** [comment]
This is not a bug. We wanted the player to be able to type other words even if they are not in the screen dialog. That also allows hidden dialog and secret quests. For example, later in the game, someone asks you to go see a character and tell him "Jasper". "Jasper" is not part of the visible dialog tree but typing it while talking to the guy will unlock a secret dialog.

**Comment by Nestastnikos** [comment]
@VirginRedemption  Thanks for the explanation. If It should work that way, I am all fired up now :)

However I just want to raise one point for consideration related to this non-issue anyway. Well if the conversation is split into multiple dialogs ie if you speak with one of the worshippers, the conversation can go in two-directions, eg:
1. Tree of life
2. The Queen

What actually confused me (and why I thought that this is a bug) is that while you are kept in the one dialogue, it did not make much sense to me to jump to the middle of another (eg you speak about the queen and all of the sudden I am in the middle of the dialogue about the tree of life).

Also the availability of all the words means that you can jump forward as well as jump backwards, which creates possibility to lead non-logical and non-authentic dialogues. To be capable of entering the secret dialogue at any point of the conversation may create scenario where the player may not always jump into the beginning of it, but to the middle or to the end of that secret dialogue (which may be sometimes the source of the confusion if that secret dialogue should give him a quest).

If this was how it was designed then everything is alright, those are just my thoughts about the topic. :)

**Comment by VirginRedemption** [comment]
I get your point and we'll discuss your feedback. Thanks
