### ISSUE TITLE
Incorrect grammar case of interactive word is expected to be typed in Polish

### ISSUE THREAD

**Issue by Nestastnikos** [FishingCactus/NanotaleEarlyAccessBugs#60]
**Describe the bug**
When the Rosalind is inside the dialogue and needs to interact with the character by typing uppercased words. Some words needs to be typed in different grammar case than they are displayed.

**To Reproduce**
1. Precondition: The game should have Gameplay language set to Polish.
2. Precondition: Rosalind is in dialogue with character nearby Tree of life.
3. Type Drzewa (which is the uppercased word displayed in bubble).

**Actual behavior**
The part "Drzew" is accepted and "a" is ignored.

**Expected behavior**
The word should be accepted and next bubble should popup.

**Screenshots**
![20191031221614_1](https://user-images.githubusercontent.com/23109654/68038096-700c6f80-fcc9-11e9-89d1-509a067dff8a.jpg)

**Additional context**
Actually the problem can be solved by typing "Drzewo" which is the nominative case of word tree in Polish. I saw that it is not rule that the word needs to be always typed in nominative case, in another dialogue, the expected word was "królowa" which is the nominative case for queen, but to trigger next bubble I needed to type "królową" which is the accusative or instrumental case. The grammar cases are mixed in general, there is not any general pattern how the words are cases are mixed. However the words are displayed correctly (only in the background were expected their another grammar forms for interaction).

EDIT: The word "królową" worked because that word is interactive in another bubble in that dialogue.
![20191101181603_1](https://user-images.githubusercontent.com/23109654/68044271-48bc9f00-fcd7-11e9-8e27-6504bb7c4798.jpg)

**Comment by DavidTheDesigner** [comment]
Fixed in loca

**Comment by ZinaDerudder** [comment]
@Nestastnikos thanks for that bug report =)
The fix for this issue will be implemented in a future update.
