### ISSUE TITLE
Mismatch of interactive words in the dialogue

### ISSUE THREAD

**Issue by Nestastnikos** [FishingCactus/NanotaleEarlyAccessBugs#61]
**Describe the bug**
Some dialogues have mismatched their interactive words, which means that some words are maybe incorrectly translated in given context, or incorrect word is displayed as interactive one.

**To Reproduce**
1. Precondition: Gameplay language of the game is set to Polish.
2. Precondition: Rosalind in the dialogue with the character nearby tree of life.
3. Type "Ciężko".

**Actual behavior**
Nothing happens.

**Expected behavior**
Next bubble for that particular word should be triggered.

**Screenshots**
![20191031221245_1](https://user-images.githubusercontent.com/23109654/68040826-67b73300-fccf-11e9-96b4-fe5e03665ecf.jpg)

**Additional context**
I did not find the way how to trigger word "Ciężko" but when I compared the dialogue to english one, the uppercased word is "injured" which is not the english equivalent to "ciężko". The equivalent in that particular dialogue is word "ranny" which is also in that bubble but is not uppercased. The word ranny triggered next (and correct) bubble even though it is not uppercased (when compared to english equivalent).

What I also realized is that when you type "pa" (bye in english) which I did not even find as a part of the dialogue, it triggers the new bubble, and when "pa" is typed the second time, it quits that particular dialogue. I don't think that this is correct behavior even if this was meant as feature, since not all dialogues are quit with "pa".

**Comment by VirginRedemption** [comment]
Thank you! These bugs have been fixed.
