### ISSUE TITLE
Respawned creatures after relaunch of the game

### ISSUE THREAD

**Issue by Nestastnikos** [FishingCactus/NanotaleEarlyAccessBugs#62]
**Describe the bug**
After the game is progressed and the saves are made, the state of the creatures is not saved and all the creatures are respawned after the game is relaunched. This counts in killed creatures and also sheeps which were pushed/pulled.

**To Reproduce**
1. Precondition: Rosalind is in the part where she received the skills to pull/push the enemies.
2. Follow the story until you get to the open field with the enemies (see screenshot).
3. Quit the game and relaunch it.
4. (In main menu) Hit start.
5. Wait for game to load.
6. Check surroundings.

**Actual behavior**
The killed creatures are respawned. The pulled/pushed sheeps are on it's original place.

**Expected behavior**
Everything should be returned to it's state before the game was quit.

**Screenshots**
![20191101183540_1](https://user-images.githubusercontent.com/23109654/68045429-c1bcf600-fcd9-11e9-95b2-20b2611de861.jpg)
![20191101184835_1](https://user-images.githubusercontent.com/23109654/68045440-c84b6d80-fcd9-11e9-86b6-bf80de3f4284.jpg)

**Comment by Nestastnikos** [comment]
Now when I gave it second thought, the drawback here is that some parts may be impossible to complete, if the checkpoint is hit and the player killed the enemy which he should use for some action (eg. it should allow him to cast a spell). There will be no way of reverting to the previous checkpoint or discard the current one. The player will need to play from the start if he did not make saves over time.

On the other hand is it real pain to kill/avoid everything every time you relaunch the game.

**Comment by grumiauxl** [comment]
Hi @Nestastnikos, this is intended behavior for now, leaving the enemies in the game after respawn is to avoid, like you said, blocking situations, but it's also to please people who enjoy typing just for the sake of it. In theory, if you just feel like going further in the story after a respawn, you can quite easily avoid enemies by hiding or running with the fox.
Thanks for your feedback, enjoy the game!

**Comment by Nestastnikos** [comment]
@grumiauxl I totally agree with what you've written regarding enemies. However what about those creature objects which can be pushed/pulled by AoE spells (like sheeps) ?

Isn't it like a part of the story which needed to be completed in order to further progress the game? I mean, if you don't do it for the first time, you cannot move to the other parts of the game. With the enemies you can usually avoid them to continue in the story (I mean the enemies in environment not arena fights).
