### ISSUE TITLE
Incorrect hint displayed after the pull/push skills are acquired

### ISSUE THREAD

**Issue by Nestastnikos** [FishingCactus/NanotaleEarlyAccessBugs#63]
**Describe the bug**
The hint which should guide the player how to use the skills has mismatch with the actual UI.

**To Reproduce**
1. Precondition: The pull/push skill has been acquired.
2. Read the displayed hint.

**Actual behavior**
The hint displays word "Strong" as "Mocno".

**Expected behavior**
The hint should display word "Dużo" or the word "Dużo" should become "Mocno" in the UI.

**Screenshots**
![20191101182428_1 - Copy](https://user-images.githubusercontent.com/23109654/68046076-4b20f800-fcdb-11e9-973a-7fc42fb65ac2.jpg)

**Additional context**
I am not native Polish speaker, but I'd say that MOCNO is more preferable even in UI since it is typed easier compared to DUŻO. Both expresses the same thing, but DUŻO is more like "huge" than strong (but in Polish, both can be used in this context).

**Comment by VirginRedemption** [comment]
yep so, we'll replace MOCNO by DUŻO because "huge" is what we meant. I fixed it in the localization file and it should be in the next update. Thank you!
