### ISSUE TITLE
Limited line of sights of basic creatures

### ISSUE THREAD

**Issue by Nestastnikos** [FishingCactus/NanotaleEarlyAccessBugs#65]
**Describe the bug**
The line of sight of creatures, or the threshold when they spot Rosalind is weirdly set. The roofs and bridges are especially problematic for their line of sight.

**To Reproduce**
Try to run around the roofs or bridges to see for yourself.

**Expected behavior**
The line of sight should be more precise.

**Screenshots**
The situation on the bridge, actually the creature is only very short distance from Rosalind but she cannot be seen.
![20191101135536_1](https://user-images.githubusercontent.com/23109654/68047513-dea7f800-fcde-11e9-8f10-e19caebf0495.jpg)
![20191101135508_1](https://user-images.githubusercontent.com/23109654/68047514-df408e80-fcde-11e9-93db-07f34f8990e2.jpg)

Another way of very limited line of sight is in the short distance but out of sharp angle.
![20191101183455_1](https://user-images.githubusercontent.com/23109654/68047798-73aaf100-fcdf-11e9-873b-3b8b7736de5d.jpg)
![20191101183448_1 - Copy](https://user-images.githubusercontent.com/23109654/68047801-74438780-fcdf-11e9-8399-2bd7e66dabb8.jpg)

**Comment by ZinaDerudder** [comment]
@TheThibz Navmesh Related.
Will be fixed ina  future update.
