### ISSUE TITLE
Broken paging in Encyklopedia

### ISSUE THREAD

**Issue by Nestastnikos** [FishingCactus/NanotaleEarlyAccessBugs#68]
**Describe the bug**
Navigating between the pages in Encyklopedia is not working as expected. Once the page is turned (to the right or to the left) it is not possible to come back.

**To Reproduce**
1. Precondition: The flowers Stalligush, Creeper's brush and Stardew should be already discovered.
2. Precondition: Game is launched and started (inside the level).
3. Open the in-game menu.
4. Hit Encyklopedia -> Flowers.
5. Click L Ctrl label.
6. Click R Ctrl label.

**Actual behavior** 
The plants did not appear again.

**Expected behavior**
The plants Stalligush and Creeper's brush should be displayed again.

**Screenshots**
Initial state
![20191101220826_1](https://user-images.githubusercontent.com/23109654/68056944-c216ba80-fcf4-11e9-9b4b-dc88c450e62b.jpg)

**Additional context**
Actually if only Encyklopedia -> Plants -> L Ctrl is clicked and after that Plants are clicked again, the Stardew is displayed. After that If the R Ctrl -> Plants are clicked , then the initial state is achieved once again.

![20191101220841_1](https://user-images.githubusercontent.com/23109654/68057078-25a0e800-fcf5-11e9-822d-9180ab0c3386.jpg)

**Comment by Graewynd** [comment]
This issue still exists in Update #5.  I don't find that either the R or L Ctrl keys work at all, and clicking the labels with the mouse exhibit behavior as described above.

**Comment by VirginRedemption** [comment]
That issue is still in progress. Just keeping you updated about it.
