### ISSUE TITLE
Untypable word when the substring of that word is present in range

### ISSUE THREAD

**Issue by Nestastnikos** [FishingCactus/NanotaleEarlyAccessBugs#69]
**Describe the bug**
Sometimes there are words which starts with the same letters but one may be shorter then another. In that case, the shorter one will be always triggered and the target on the longer one is lost.

**To Reproduce**
1. Precondition: Creature with the name Turgor nearby.
2. Precondition: Gameplay language is set to Polish,
3. Precondition: The Rosalind is in type mode.
4. Type "Tur". 

**Actual behavior**
The "Tu" (Pull - or literal translation is "Here") is triggered and the progress on word "Turgor" is reset to the beginning and R is treated is mistake.

**Expected behavior**
The progress on Turgor should not be reset and R should be counted.

**Screenshots**
![20191101222636_1](https://user-images.githubusercontent.com/23109654/68058955-0311cd80-fcfb-11e9-92ce-500e4fa94105.jpg)

**Comment by VirginRedemption** [comment]
Fixed. Thanks.
