### ISSUE TITLE
Water zones can be glitchy in some areas

### ISSUE THREAD

**Issue by grumiauxl** [FishingCactus/NanotaleEarlyAccessBugs#7]
![image](https://user-images.githubusercontent.com/25320773/67467339-ddc0f780-f648-11e9-83dc-2cf5e68dd8f6.png)

**Comment by grumiauxl** [comment]
![image](https://user-images.githubusercontent.com/25320773/67467380-ee716d80-f648-11e9-82f2-1aa16c2a04bd.png)

**Comment by ZinaDerudder** [comment]
Known issue. Duplicate, this one is closed.
