### ISSUE TITLE
Stuck here and cannot move every time I finish burning tree.

### ISSUE THREAD

**Issue by RianDonner** [FishingCactus/NanotaleEarlyAccessBugs#71]
![sutuck](https://user-images.githubusercontent.com/57279994/68065985-9fda6800-fd07-11e9-84a0-e7119b8c3fa9.jpg)

**Comment by grumiauxl** [comment]
Hi @RianDonner This is actually the end of the early access available content, we are missing a small typable text that should have hinted you, but you basically have reached the end of the first Biome. What you see here is the next zone which will unlock at the full release of the game.

**Comment by RianDonner** [comment]
Thanks so much! I figured this was the end just wasn't sure and got concerned after I couldn't move around. Thanks again :)
