### ISSUE TITLE
Incorrect grammar case of language name in the settings menu

### ISSUE THREAD

**Issue by ghost** [FishingCactus/NanotaleEarlyAccessBugs#72]
**Describe the bug**
When choosing language the name of Polish language is translated with error.

**To Reproduce**
1. Go to Options
2. Press '<' or '>' under 'menu and story language' until Polish
3. See error

**Actual behavior**
It states 'Polsku' under 'Gameplay language' and 'Menu  and story language'

**Expected behavior**
Should state 'Polski'.

**Screenshots**
![Uploading image.png…]()

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Graphics device: GTX 1060

**Comment by ghost** [comment]
![123](https://user-images.githubusercontent.com/57294627/68073418-56822b00-fd90-11e9-8f4d-42db16906d82.png)

**Comment by VirginRedemption** [comment]
Thank you! We'll check that with the translators.

**Comment by DavidTheDesigner** [comment]
Fixed in loca
