### ISSUE TITLE
Still lagging typing issue on "...rat enemy" (update #5)

### ISSUE THREAD

**Issue by Graewynd** [FishingCactus/NanotaleEarlyAccessBugs#74]
Wanted to re-open a previous issue, but couldn't figure out if it can be done.
In update #5, was still able to get the highlight to lag the typing on the upgrade "Increased damage on rat enemy" between the "rat" and "enemy" (typing the "enemy" was lagging the actual typing). Sorry, but can't remember if I typed a space between rat and enemy, but I had tried both space and no space on the earlier word separations and they didn't have an issue.

**Comment by ZinaDerudder** [comment]
Hello @Graewynd 
I'm trying to reproduce this issue, and I cannot manage to do it.
If you are facing this issue again, could you let us know?
Thank you in advance =)

**Comment by Graewynd** [comment]
Yes, it still happens, version 0.5.7341.25212-EA-r (and by the way, I still suggest an easy version number be displayed on the ESC screen).
When typing to select the gift, the first E in ENEMY does not get dimmed until the N is then pressed (which then dims the E, but not the N), so it looks as if there is a lag on the typing.  It does catch up after the second E, I think.
![image](https://user-images.githubusercontent.com/57119636/76632492-b3010e00-6519-11ea-9288-da39d24902c0.png)

**Comment by ZinaDerudder** [comment]
**Info for team**
Also occurs with skill "Increased damage on carrier enemies"
