### ISSUE TITLE
Conversation with Kai issue (update #5)

### ISSUE THREAD

**Issue by Graewynd** [FishingCactus/NanotaleEarlyAccessBugs#75]
In the initial conversation with Kai, could not complete the word HELL - type the second L didn't do anything, then typing a third L cleared the HELL highlights and starting highlighting LOST.
![image](https://user-images.githubusercontent.com/57119636/68421083-928c0600-016b-11ea-9536-7606ebcf66c9.png)

**Comment by Graewynd** [comment]
Meant to say this is with update #5.

**Comment by VirginRedemption** [comment]
Thanks. It's fixed.
