### ISSUE TITLE
Queen dialogue almost-lock (update #5)

### ISSUE THREAD

**Issue by Graewynd** [FishingCactus/NanotaleEarlyAccessBugs#76]
After winning the queen battle, I got all the queen dialogue about needing to burn the tree, but *no* indication about teleport ability.  I could not move after this dialogue (ESDF), but was able to teleport to the teleport area, and then move.  I don't know the true intent here, but it seems to me I should be able to go to other areas before climbing the tree (areas that I know exist because I visited them in previous updates), as the early-access portion is over once the tree is burned.
![image](https://user-images.githubusercontent.com/57119636/68430814-ce7c9680-017e-11ea-8075-9dc54e395163.png)

**Comment by Graewynd** [comment]
Follow-on, I was able to get back down from the 2nd teleport area, by burning the root growth.  But this was done by *falling through* the root, as shown here.  Was this intended?
![image](https://user-images.githubusercontent.com/57119636/68431514-69c23b80-0180-11ea-9bd7-53edbbcdceb7.png)

**Comment by Graewynd** [comment]
Also, when I later came back to the queen and talked to her again, THEN she told me she gave me the power of teleportation.

**Comment by Graewynd** [comment]
Later, when I came back to climb the tree, the teleport to the 2nd level was no longer available, and I was stuck.
![image](https://user-images.githubusercontent.com/57119636/68441593-9edc8700-019c-11ea-963f-342b320046d5.png)

**Comment by Graewynd** [comment]
I should also mention in case it is at all significant, that after I fell through the branch (above) and was then able to explore the world via teleporting areas, that at some point (and I don't remember when it occurred - maybe after a respawn) the camera was rotated 180 degrees from "normal" and it stayed that way even when going back to areas previously traversed, except when I engaged in dialogues with people it would temporarily rotate back to "normal" until exiting the dialogue.  This is why some of the pictures taken for issues after this point are rotated 180 degrees.

**Comment by VirginRedemption** [comment]
All fixed
