### ISSUE TITLE
Sharp spell repeats (update #5)

### ISSUE THREAD

**Issue by Graewynd** [FishingCactus/NanotaleEarlyAccessBugs#77]
This happened in earlier updates as well.  The Sharp spell addition showed up again in one of the Level Up choices even though I already had it taken it (and had it in the spell dialogue).

**Comment by Graewynd** [comment]
Also had the Long (and Sharp) repeat on following Level Up window.

**Comment by Ruvah** [comment]
Hello!

Apologies for the inconvenience, there was an issue with upgrade talents not being removed from the list if there were no new ones to replace it with (which would appear when reaching close to the maximum reachable level in the EA). This is fixed internally and will be on a live version soon. 
Have a great day!
