### ISSUE TITLE
No text bubble and sink-to-death (update #5)

### ISSUE THREAD

**Issue by Graewynd** [FishingCactus/NanotaleEarlyAccessBugs#78]
The plant shown has no text bubble when approached, and if the rock shown by the arrow is walked on, Rosalind sinks down, down, down to her death.
![image](https://user-images.githubusercontent.com/57119636/68432280-24067280-0182-11ea-9cc0-cfa6f2d838be.png)
![image](https://user-images.githubusercontent.com/57119636/68432304-2f599e00-0182-11ea-8488-10531472b559.png)

**Comment by TheThibz** [comment]
@InnoAnca Missing/Misplaced wall
For the word, the lore is missing in loca document

**Comment by InnoAnca** [comment]
art wise it is fixed, wall collider added, a rock on the floor too, to avoid falling

**Comment by VirginRedemption** [comment]
All Fixed
