### ISSUE TITLE
Blocked on bridge (update #5)

### ISSUE THREAD

**Issue by Graewynd** [FishingCactus/NanotaleEarlyAccessBugs#79]
Blocked from going south on this bridge for no obvious reason
![image](https://user-images.githubusercontent.com/57119636/68437111-fb847580-018d-11ea-9cd0-e25925621011.png)
![image](https://user-images.githubusercontent.com/57119636/68437116-0212ed00-018e-11ea-8b64-b419e9ab7b8f.png)

**Comment by InnoAnca** [comment]
fixed
