### ISSUE TITLE
No text bubble here? (update #5)

### ISSUE THREAD

**Issue by Graewynd** [FishingCactus/NanotaleEarlyAccessBugs#80]
Had to burn through thorns to get here.  No text bubble on the rock - seems like there should have been?
![image](https://user-images.githubusercontent.com/57119636/68437344-aac14c80-018e-11ea-8f09-7bd2bcc9bdbd.png)
![image](https://user-images.githubusercontent.com/57119636/68437361-b3198780-018e-11ea-9041-bf43ee773ddc.png)

**Comment by ZinaDerudder** [comment]
Hey @Graewynd 
Thanks for you bug report.
It has been fixed.
