### ISSUE TITLE
Stuck not able to complete dialogue, respawn locks camera (update #5)

### ISSUE THREAD

**Issue by Graewynd** [FishingCactus/NanotaleEarlyAccessBugs#81]
Stuck at this point in dialogue. Neither spacebar nor anything else seems to work.  Can't move, etc.  Will have to respawn.  Took the "LOST" path in the dialogue.
![image](https://user-images.githubusercontent.com/57119636/68437745-d1cc4e00-018f-11ea-8128-852f823aadc8.png)
NOPE - Respawn didn't work - Rosalind *vanished*!  Will try to quit and restart.
![image](https://user-images.githubusercontent.com/57119636/68437817-18ba4380-0190-11ea-8ad2-1aa5afb746a5.png)
Quit and restart worked (Rosalind spawned over to left of the character).  Tried the dialogue with the HELP option - same result as before.  BUT, turned out on the respawn that Rosalind did spawn over to the left, but the camera was locked on the character's text and would not move.  I could bring Rosalind into the picture (since I knew where she was), but camera was dead.  Have to quit and restart to get past this bug.

**Comment by VirginRedemption** [comment]
Fixed in the last update.
