### ISSUE TITLE
Really stuck after teleport, no way out (update #5)

### ISSUE THREAD

**Issue by Graewynd** [FishingCactus/NanotaleEarlyAccessBugs#82]
Unless I'm missing something, I'm stuck on this plateau after teleporting there.  The bridge is blocked and there is nothing nearby to burn with, and the teleport below is too far away to have any words appear.  Both respawn and quit/restart put me back on the plateau.  Seems like game over.
![image](https://user-images.githubusercontent.com/57119636/68438906-bebb7d00-0193-11ea-88c8-07abc573bf1e.png)
![image](https://user-images.githubusercontent.com/57119636/68439000-0d691700-0194-11ea-9a63-6a36b3d714c8.png)
![image](https://user-images.githubusercontent.com/57119636/68439043-2e316c80-0194-11ea-81ed-31b95ebb7251.png)

**Comment by Graewynd** [comment]
Never mind.  I found a solution to burn.  Tricky.

**Comment by Mihanasan** [comment]
Hi, I have the exact same problem @Graewynd . Could you please explain me how you burnt it ? I tried all combinations but it doesn't reach the goal... Thanks in advance !

**Comment by Graewynd** [comment]
Sorry @Mihanasan, but it has been so long since I've played this that I don't remember a thing about it.  Wish I could help you.

**Comment by Mihanasan** [comment]
No problem @Graewynd , thank you very much for your reply, I'll try again !
