### ISSUE TITLE
Update #6 (I believe) - stuck without FIRE

### ISSUE THREAD

**Issue by Graewynd** [FishingCactus/NanotaleEarlyAccessBugs#84]
This should be update #6.  NOTE: There really should be a clear Version # in the ESC menu (not just on the Main Menu page) and I'd suggest it relate directly to the Update number.  The Version # on the Main Menu is 0.5.7256.30595-EA-r.  This would allow us to be sure that Steam updated to your latest version.

I reached the area below, and all routes out are blocked.  I somehow reached here and did not receive the FIRE spell, so can't burn what I need to escape the area.  Sorry, but I can't tell you how it happened - I thought I did everything pretty "normally", this being about the 6th time through.
![image](https://user-images.githubusercontent.com/57119636/69106538-ad4c5d80-0a3c-11ea-824e-6ea61f8e188d.png)
This is the guy that wants me to talk to the Queen and won't let me go back, and as you can see I don't have FIRE so can't burn the roots or the brambles.
![image](https://user-images.githubusercontent.com/57119636/69106581-d10fa380-0a3c-11ea-8531-80e8b23d2d5f.png)
I thought I should have received FIRE from the area below, but did not:
![image](https://user-images.githubusercontent.com/57119636/69106817-89d5e280-0a3d-11ea-914f-478935b95970.png)

**Comment by ZinaDerudder** [comment]
Hello @Graewynd 
Do you manage to reproduce this bug?
Did you do something special?

**Comment by Graewynd** [comment]
As I said previously, I don't know how this happened, unfortunately.  I just played through again and did not encounter this situation, so I can't help further.
