### ISSUE TITLE
Update #6, not pausing enemies when Lore dialogue pops up

### ISSUE THREAD

**Issue by Graewynd** [FishingCactus/NanotaleEarlyAccessBugs#85]
I know this has been mentioned before in various contexts.  I had just typed the name on the flower below (MAIDEN) and received the pop-up where I had to type a couple words to get the Lore on the flower.  However, the snail dude kept coming and hitting me while I was trying to type the words, and there is no escape until that is done.  Just doesn't seem right, if those pop-ups can happen when they are not expected.
![image](https://user-images.githubusercontent.com/57119636/69107080-4039c780-0a3e-11ea-8381-5b89b491ebca.png)

**Comment by ZinaDerudder** [comment]
fixed. Enemies are stopped when a lore pop-up is displayed.
