### ISSUE TITLE
Update #6, untypeable word

### ISSUE THREAD

**Issue by Graewynd** [FishingCactus/NanotaleEarlyAccessBugs#86]
In the dialogue box below, the word HELL can't be typed.  It gets to HEL then the next L starts the word LOST.  If instead the LOS is typed, then try to type the H, it does not appear that the H was taken (it doesn't go dim), but it actually was, since typing an E would then go dim.  But the full HELL still can't be completed.
![image](https://user-images.githubusercontent.com/57119636/69107267-c8b86800-0a3e-11ea-9437-13148f60a758.png)

**Comment by Nestastnikos** [comment]
I've found similar issue (little different), but in Polish language. I could type the word ŻLE, but when I did so, I even heard the sound of successful completion of the word. However nothing happened. No bubble appeared.
![20191118220653_1](https://user-images.githubusercontent.com/23109654/69190588-fd045500-0b20-11ea-897c-680c23832256.jpg)

**Comment by ZinaDerudder** [comment]
It's fixed. Thank you for the report =)
