### ISSUE TITLE
Inconsistency in dialogue handling

### ISSUE THREAD

**Issue by Nestastnikos** [FishingCactus/NanotaleEarlyAccessBugs#87]
**Describe the bug**
The behavior in dialogues is quite inconsistent sometimes.  After the dialogue with some character is finished, the dialogue with that character always start with the last (ending) bubble (let's call it Char 1). However when the Rosalind speaks with Char 2, and then comes back to Char 1, the dialogue will again start from the beginning.

**To Reproduce**
1. Approach character blocking the way, nearby the tree of life.
2. Complete the dialogue with him.
3. Start the dialogue again.
4. Check the bubble (screen 1).
5. Complete the dialogue with another character standing nearby.
6. Start the dialogue with the second character again.
7. Check the bubble (screen 2).
8. Start the dialogue with the firstly approached character.
9. Check bubble. (screen 3)

**Actual behavior**
The dialogue now starts from the beginning.

**Expected behavior**
When interacting with the character, it should always start from the beginning OR always display just last bubble.

**Screenshots**
![20191118221147_1](https://user-images.githubusercontent.com/23109654/69174189-9754a080-0b01-11ea-97e9-80890f4e2cc7.jpg)
![20191118221206_1](https://user-images.githubusercontent.com/23109654/69174191-9754a080-0b01-11ea-8978-b4ee75037ffa.jpg)
![20191118221043_1](https://user-images.githubusercontent.com/23109654/69174187-9754a080-0b01-11ea-83a3-f148c0c76e00.jpg)

**Additional context**
I don't know what was the intention behind it, how the interaction should look like. Actually some characters like for example, the one which wants to lead the secret dialogue always displays the last bubble after the secret dialogue is finished. On the other hand Kai, Queen etc. always start the dialogue from the beginning.

If some characters should always repeat the dialogue, while others should not, it makes sense. However if some characters should not repeat it, then there should not be a way how to start it all over again.

**Comment by ZinaDerudder** [comment]
Thanks, we'll see how to handle that.
