### ISSUE TITLE
Burnt mana on plant discovery

### ISSUE THREAD

**Issue by Nestastnikos** [FishingCactus/NanotaleEarlyAccessBugs#88]
**Describe the bug**
When the spell is activated (pull/push/fire) and the plant is discovered, the mana for that spell is burnt even though the spell is not casted.

**To Reproduce**
1. Precondition: Pull/Push skills acquired.
2. Activate PUSH spell (or PULL whatever).
3. Go nearby plant that has not been discovered yet.
4. Hit spacebar.
5. Type the displayed word to discover the plant.
6. Check mana bar.

**Actual behavior**
The activated spell is still active on Rosalind, but the mana for that spell was burnt.

**Expected behavior**
The mana should not be burnt on plant discovery.

**Screenshots**
![20191118222936_1 - Copy](https://user-images.githubusercontent.com/23109654/69183950-34203980-0b14-11ea-8e2b-86e74cae40d3.jpg)

**Additional context**
It may not be that visible on the screenshot, but that milk area around the Rosalind is actually shown effect of active spell.

**Comment by Nestastnikos** [comment]
I've found similar issue with the dialogs. When the Rosalind have activated any spell (pull/push/fire) and then she starts the dialogue, the mana for that spell is used, but it does not produce any effect (as expected).

![20191122200519_1](https://user-images.githubusercontent.com/23109654/69453266-d550ff00-0d63-11ea-9ed8-c9b88abd6a48.jpg)

**Comment by Ruvah** [comment]
Fixed :)
