### ISSUE TITLE
Not stopped Giant creature during the Plant discovery

### ISSUE THREAD

**Issue by Nestastnikos** [FishingCactus/NanotaleEarlyAccessBugs#89]
**Describe the bug**
The discovery of the plant display an interactive window which requires to type some words in order to fully discover the plant / or the object. If the Giant creature is nearby, it starts to prepare for charge, when in meantime the Plant discovery is triggered and the window pops-up, the type mode is entered (and hence the player cannot move). If the Giant creature hits the Rosalind, she is thrown (and stunned) and the type mode is interrupted. In this state it is not possible to enter the type mode again.

**To Reproduce**
1. Precondition: Giant creature nearby.
2. Precondition: One plant of certain type is missing to fully discover it.
3. Bait the Giant creature to follow you.
4. Go nearby plant.
5. Wait until the Giant creature starts to charge.
6. Trigger Plant discovery.
7. Watch Giant creature.

**Actual behavior**
The Giant creature is still charging, it does not stop. The charge is then carried out.

**Expected behavior**
The charging of Giant creature should be interrupted.

**Screenshots**
![20191118223624_1](https://user-images.githubusercontent.com/23109654/69185105-5b780600-0b16-11ea-9597-96ff61a0d0d6.jpg)
![20191118223629_1 - Copy](https://user-images.githubusercontent.com/23109654/69185174-84989680-0b16-11ea-958f-9bda5cc70174.jpg)

**Additional context**
I just want to raise the point for consideration, whether the same scenario cannot occur during level up. However I did not get lucky, to prepare the setup for this scenario.

**Comment by ZinaDerudder** [comment]
Hello @Nestastnikos .
The Dash enemy behaviour has been reworked, the fix for this issue will be implemented in a future update.
