### ISSUE TITLE
Enemies cannot cross bridges

### ISSUE THREAD

**Issue by Nestastnikos** [FishingCactus/NanotaleEarlyAccessBugs#90]
**Describe the bug**
The bridges which were triggered as platform for Rosalind to move to another part are not accessible for creatures.

**To Reproduce**
1. Precondition: Enemies on the other side of the bridge.
2. Let the enemies spot you.
3. Watch them going towards you.

**Actual behavior**
The enemies are not capable of crossing the bridge and hence they will never reach you.

**Expected behavior**
The enemies should be capable of crossing the bridge.

**Screenshots**
![20191101153441_1](https://user-images.githubusercontent.com/23109654/69185907-e5749e80-0b17-11ea-94a9-0471c9365a02.jpg)

**Comment by ZinaDerudder** [comment]
Hello @Nestastnikos .
This issue is due to navmesh issue.
It's currently being reworked. This should be fixed in a future update.

**Comment by ZinaDerudder** [comment]
Fixed
