### ISSUE TITLE
Missing animations when LONG attribute is active

### ISSUE THREAD

**Issue by Nestastnikos** [FishingCactus/NanotaleEarlyAccessBugs#91]
**Describe the bug**
The animation for spells are missing, when LONG attribute is active.

**To Reproduce**
1. Precondition: LONG attribute was acquired from the talents.
2. Activate PUSH spell with LONG attribute.
3. Cast it on the enemy.
4. Observe effect.

**Actual behavior**
The skill is casted, the damage to creatures is given, the PUSUH effect is applied, PUSH animation is missing.

**Expected behavior**
The animation should be visible (well how to describe how it should look like, no idea).

**Additional context**
I would like to provide some screenshots however it is hard to show this on screenshot, and the GitHub does not allow clips. Just notice this affects ALL acquired spells.

**Comment by ZinaDerudder** [comment]
Hello @Nestastnikos .
Is this bug still occuring?
If it's the case, can you record a clip and set it to me directly, as like you said, it's not supported on Git.
You can send me clip on Discord: Wyatt#9854

**Comment by Nestastnikos** [comment]
@guillaumeDerudder 
Hi, I appreciate that you are taking all my reports into account so they are not in vain :)

I would like to help you but I don't have Nanotale installed :D I think what I could do is to send you some save files, but honestly I don't believe they will be compatible since they were made 4 months ago - and the saves may not be representative, since in the later gameplays I was using glitches a lot to bypass arenas and blocking objects.

**Comment by ZinaDerudder** [comment]
Indeed, in this case, it's not really relevant.
But I'm pretty sure most of them are fixed. The game is way more stable now.
Again, thank you for helping us tracking the bugs, it's really appreciated :)
