### ISSUE TITLE
Displayed discovery text behind the discovered plant/object

### ISSUE THREAD

**Issue by Nestastnikos** [FishingCactus/NanotaleEarlyAccessBugs#94]
**Describe the bug**
Sometimes during the discovery of a plant, the text was displayed behind the object and hence not readable.

**Expected behavior**
The text should appear in front of the object.

**Screenshots**
![20191118223217_1](https://user-images.githubusercontent.com/23109654/69188058-0fc85b00-0b1c-11ea-8570-76d549ed47b6.jpg)

**Comment by ZinaDerudder** [comment]
Issue fixed in current Steam build.
Now a clean pop-up is displayed, in front of the analysed lore element.
Thanks for reporting it =)
